### ISSUE TITLE
Alloy is not defined 

### ISSUE THREAD

**Issue by mbilwar** [FokkeZB/nl.fokkezb.loading#36]
Hello,

I am facing this issue from last 2 days but couldn't find the solution for this issue.

Could you please check and revert back the issue if possible.

Error: Alloy is not defined.

Activity: App is closed. When Clicked on Local Notification it will open the app but unfortunately it will crash the app by showing above error message and when i click on kill it will load app again without any error message.

Alloy.js: 

//Init Loader
Alloy.Globals.loading = Alloy.createWidget("nl.fokkezb.loading");

jira Link: https://jira.appcelerator.org/browse/ALOY-1504 

Screenshot is there in jira link.

Thank you in advance.

**Comment by FokkeZB** [comment]
Hi @mbilwar,

As suggested at https://jira.appcelerator.org/browse/ALOY-1504 this is an issue with Titanium activities initiated through other means than launching the app from the homescreen. Somehow, the globals declared in `app.js` (and `alloy.js` in Alloy projects), including `alloy` are not available.

Closing this issue here for further discussion on JIRA.
